name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou a branch que você usa para deploy
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2  # Faz o checkout do repositório

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Definir PYTHONPATH
      run: echo "PYTHONPATH=$PWD/app" >> $GITHUB_ENV

    - name: Instalar dependências
      run: |
        python -m venv venv  # Cria o ambiente virtual
        source venv/bin/activate  # Ativa o ambiente
        pip install --upgrade pip  # Atualiza o pip
        pip install -r requirements.txt  # Instala as dependências
        pip install pytest  # Instala pytest

    - name: Rodar os testes com cobertura
      run: |
        source venv/bin/activate
        pytest --cov=app tests/

    - name: Rodar a aplicação 
      run: |
        source venv/bin/activate
        python app.py  # Simula o deploy da aplicação 

    - name: Mensagem de sucesso
      run: echo "Aplicação foi rodada com sucesso!"
