name: Deploy Flask Application

on:
  push:
    branches:
      - main  # Trigger para o branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Flask app
      run: |
        docker build -t flask-app .
        docker run -d -p 5000:5000 flask-app

    - name: Verify application is running
      run: |
        sleep 10  # Aguarda a aplicação subir
        curl -f http://localhost:5000 || exit 1  # Verifica se a aplicação está respondendo

    - name: Clean up Docker containers
      run: |
        docker ps -q --filter "ancestor=flask-app" | xargs docker stop | xargs docker rm
