name: CI/CD Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configurar banco de dados SQLite
        run: |
          source venv/bin/activate
          python -c "from app import db; db.create_all()"

      - name: Executar testes
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Simular Deploy (Opcional)
        run: echo "Simulação de deploy bem-sucedida!"
